"""initial_schema

Revision ID: ca368383a34a
Revises: 
Create Date: 2026-04-10 14:14:16.750903
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ca368383a34a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrum_teams',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contexts',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('urgency_weight', sa.Float(), nullable=False),
    sa.Column('value_weight', sa.Float(), nullable=False),
    sa.Column('alignment_weight', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['scrum_teams.team_id'], ),
    sa.PrimaryKeyConstraint('context_id')
    )
    op.create_table('dataset_uploads',
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['scrum_teams.team_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('sprints',
    sa.Column('sprint_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['scrum_teams.team_id'], ),
    sa.PrimaryKeyConstraint('sprint_id')
    )
    op.create_table('sprint_plans',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=False),
    sa.Column('selected_stories', sa.JSON(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_risk', sa.Float(), nullable=False),
    sa.Column('capacity_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.sprint_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('user_stories',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=False),
    sa.Column('business_value', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('required_skill', sa.String(length=50), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.sprint_id'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('explanations',
    sa.Column('explanation_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('value_weight', sa.Float(), nullable=True),
    sa.Column('risk_impact', sa.Float(), nullable=True),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['sprint_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], ),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanations')
    op.drop_table('user_stories')
    op.drop_table('sprint_plans')
    op.drop_table('sprints')
    op.drop_table('dataset_uploads')
    op.drop_table('contexts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scrum_teams')
    # ### end Alembic commands ###
